var John_CUVS_notes=
{
    "1:19": "1:19-37; JohnB's 3 day missions, 1:19,29,35: a) low self. b)raise HIM. c) lead to HIM. d) farwell (3:22-3:30) (2Tim 4:7) 那美好的仗我已經打過了，當跑的路我已經跑盡了，所信的道我已經守住了。 || His mission vs me. || John B. is a cross time, cross-covenants, cross-world person. || No one doubt the authenticity for John B and LaoZi, KongZi, etc. || He is the only one in the world who can be mentioned along with Jesus.  No one else can be compared with Jesus. None is like YOU in the world.",
    "1:20": "-Normal show strength but hide weakness/shortcomings.",
    "1:21": "-",
    "1:22": "-",
    "1:23": "-cross OT and NT",
    "1:24": "-",
    "1:25": "-",
    "1:26": "-",
    "1:27": "-self-humiliated",
    "1:28": "Map Bethesda (e, w, ne)",
    "1:29": "-raise Him",
    "1:30": "-raise Him",
    "1:31": "-raise Him",
    "1:32": "-testify to Him",
    "1:33": "-focus oo Him. Compare: Heraclitus see material world; LaoZi see persons; John B see Holy Spirit. What do you see?",
    "1:34": "-raise Him",
    "1:35": "Who are two disciples?Answer (1:40)",
    "1:36": "-",
    "1:37": "-",
    "1:38": "-What do you want? Jesus 1st word is a question. Compare 1st word of Serpent (Gen 3:1). Both are questions but led to different destination.&nbsp;",
    "1:39": "-4pm.",
    "1:40": "-Who is another?Why not show readers author name here? Reason: same as John B. 3 missions.&nbsp;",
    "1:41": "-",
    "1:42": "-",
    "1:43": "-",
    "1:44": "-",
    "1:45": "-",
    "1:46": "-1:11; 4:44",
    "1:47": "-dolos: craft, deceit, guile. To be no dolos doesn't mean to be able to see light.&nbsp; Anyone need HIM to see light.",
    "1:48": "-",
    "1:49": "-1:9",
    "1:50": "-?",
    "1:51": "Israel dream",
    "2:1": "-Why wedding?",
    "2:2": "-",
    "2:3": "-whenever absent or need, look for HIM",
    "2:4": "-His time.No rush, patient, obedient, wait and see.&nbsp;",
    "2:5": "-How to obey, no think, no asking",
    "2:6": "-",
    "2:7": "-",
    "2:8": "-",
    "2:9": "-",
    "2:10": "-",
    "2:11": "-1st sign, glory, believe.",
    "2:12": "-",
    "2:13": "-1st passover",
    "2:14": "-",
    "2:15": "-",
    "2:16": "-Order Issue With Synoptics. Transcend Time/Space",
    "2:17": "-agape",
    "2:18": "-",
    "2:19": "-",
    "2:20": "-",
    "2:21": "-",
    "2:22": "-reminder",
    "2:23": "-many signs not written here!",
    "2:24": "-why? timing, obedience. Gen",
    "2:25": "-Gen6:5耶和華見人在地上罪惡很大，終日所思想的盡都是惡，6耶和華就後悔造人在地上，心中憂傷。",
    "3:1": "-",
    "3:2": "-",
    "3:3": "-",
    "3:4": "-",
    "3:5": "-",
    "3:6": "-hard working cannot convert fresh to spirit",
    "3:7": "-marvel.",
    "3:8": "-In Hebrew, Ruahee=wind, breath, spirit&nbsp;",
    "3:9": "-",
    "3:10": "-",
    "3:11": "-Who are \"We\"=trinity+believers&nbsp;",
    "3:12": "-Believe and obedience.",
    "3:13": "-Echo/Elie left but never came back. Jesus willing to come cause of love.",
    "3:14": "-ot prediction",
    "3:15": "-what is 'believe'?",
    "3:16": "-No one die of faith.",
    "3:17": "-agap:salvation, not judge",
    "3:18": "-1st def for sin.&nbsp;",
    "3:19": "-2nd def sin",
    "3:20": "-",
    "3:21": "-",
    "3:22": "-",
    "3:23": "-Like many ancient places, we don't know exactly where Aenon near Salim was located. One strong possibility is somewhere between the Dead Sea and the Sea of Galilee. The Greek word&nbsp; aenon&nbsp;literally means \"springs,\" so there was probably a natural fountain or other water source there.",
    "3:24": "-",
    "3:25": "-",
    "3:26": "-",
    "3:27": "-human effort call to help fr God",
    "3:28": "-",
    "3:29": "-2",
    "3:30": "-John B. farwell to the world. || model of Christian's life. (1:19)",
    "3:31": "-",
    "3:32": "-",
    "3:33": "-",
    "3:34": "-",
    "3:35": "-",
    "3:36": "-",
    "4:1": "-",
    "4:2": "-",
    "4:3": "-",
    "4:4": "-",
    "4:5": "-",
    "4:6": "-",
    "4:7": "-",
    "4:8": "-",
    "4:9": "-",
    "4:10": "-",
    "4:11": "-",
    "4:12": "-",
    "4:13": "-",
    "4:14": "-",
    "4:15": "-",
    "4:16": "-",
    "4:17": "-",
    "4:18": "-",
    "4:19": "-",
    "4:20": "-",
    "4:21": "-",
    "4:22": "-",
    "4:23": "-",
    "4:24": "-Ritualism",
    "4:25": "-",
    "4:26": "-",
    "4:27": "-why wonder?",
    "4:28": "-",
    "4:29": "-",
    "4:30": "-",
    "4:31": "-",
    "4:32": "-",
    "4:33": "-",
    "4:34": "-",
    "4:35": "-",
    "4:36": "-",
    "4:37": "-",
    "4:38": "-",
    "4:39": "-",
    "4:40": "-",
    "4:41": "-",
    "4:42": "-",
    "4:43": "-",
    "4:44": "-prologue",
    "4:45": "-",
    "4:46": "-",
    "4:47": "-",
    "4:48": "-",
    "4:49": "-",
    "4:50": "-",
    "4:51": "-",
    "4:52": "-",
    "4:53": "-",
    "4:54": "-2nd&nbsp;"
}