// fr http://users.humboldt.edu/jwpowell/heraclitusTransBillHarris.pdf

var Heraclitus_Fragments_Eng={
    "1": "Although this Logos is eternally valid, yet men are unable to understand it -- not only before hearing it, but even after they have heard it for the first time. That is to say, although all things come to pass in accordance with this Logos, men seem to be quite without any experience of it - - - at least if they are judged in the light of such words and deeds as I am here setting forth according to its nature, and to specify how it behaves. Other men, on the contrary, are as unaware of what they do when awake as they are when asleep. (1)",
    "2": "We should let ourselves be guided by what is common to all. Yet, although the Logos is common to all, most men live as if each of them had a private intelligence of his own.",
    "3": "Men who love wisdom should acquaint themselves with a great many particulars.",
    "4": "Seekers after gold dig up much earth and find little.",
    "5": "Let us not make arbitrary conjectures about the greatest matters.",
    "6": "Much learning does not teach understanding, otherwise it would have taught Hesiod and Pythagoras, Xenophanes and Hecataeus.",
    "7": "Of those whose discourses I have heard there is not one who attains to the realization that wisdom stands apart from all else.",
    "8": "I have searched myself.",
    "9": "It pertains to all men to know themselves and to be temperate.",
    "10": "To be temperate is the greatest virtue. Wisdom consists in speaking and acting the truth, giving heed to the nature of things.",
    "11": "The things of which there can be sight, hearing, and learning ---- these are what I especially prize.",
    "12": "Eyes are more accurate witnesses than ears.",
    "13": "Eyes and ears are bad witnesses to men having barbarian souls.",
    "14": "One should not act or speak as if he were asleep.",
    "15": "The waking have one world in common,",
    "16": "Death is what we see when awake , when we are asleep it is dreams.",
    "17": "Nature loves to hide itself",
    "18": "The lord whose oracle is at Delphi neither speaks nor conceals, but gives signs.",
    "19": "Unless you expect the unexpected you will never find truth, for it is hard to discover and hard to attain.",
    "20": "They do not step into the same rivers . It is other and still other waters that are flowing.",
    "21": "You cannot step twice into the same river, for other waters and yet others go ever flowing on. They go forward and back again.",
    "22": "Cool things become warm, the warm grows cool, the moist dries, the parched becomes moist.",
    "23": "It is in changing that things find repose.",
    "24": "Time is a child moving counters in a game; the royal power is a child's.",
    "25": "War is both father and king of all, some he has shown forth as gods and others as men, some he has made slaves and others free.",
    "26": "It should be understood that war is the common condition, that strife is justice, and that all things come to pass through the compulsion of strife.",
    "27": "Homer was wrong in saying, \"Would that strife might perish from amongst gods and men\" . For if that were to occur, then all things would cease to exist.",
    "28": "28. There is exchange of all things for fire and of fire for all things, as there is of wares for gold and of gold for wares.",
    "29": "This universe, which is the same for all, has not been made by any god or man, but it always has been is, and will be an ever-living fire, kindling itself by regular measures and going out by regular measures.",
    "30": "He calls it: craving and satiety.",
    "31": "It throws apart and then brings together again; it advances and retires.",
    "32": "The transformations of fire -- first, sea; and of sea, half becomes earth and half the lightning-flash.",
    "33": "When earth has melted into sea, the resultant amount is the same as there had been before sea became earth.",
    "34": "Fire lives in the death of earth, air in the death of fire, water in the death of air, and earth in the death of water.",
    "35": "The thunderbolt pilots all things through all things.",
    "36": "The sun is , as H. states, not only new each day, but forever continually new.",
    "37": "The sun is the breadth of a man's foot.",
    "38": "If there were no sun, the other stars would not suffice to prevent its being night.",
    "39": "The boundary line of evening and morning is the Bear; and opposite the Bear is the boundary of bright Zeus.",
    "40": "The fairest universe is but a heap of rubbish piled up at random.",
    "41": "Every beast is driven to pasture by a blow",
    "42": "42. You could not discover the limits of soul, even if you traveled by every path in order to do so; such is the depth of its meaning.",
    "43": "Soul is the vaporization out of which everything else is composed; more-over it is the least corporeal of things and is in ceaseless flux, for the moving world can only be known by what is in motion. (.)",
    "44": "Souls are vaporized from what is moist.",
    "45": "Soul has its own inner law of growth.",
    "46": "A dry soul is wisest and best. The best and wisest soul is a dry beam of light.",
    "47": "Souls take pleasure in becoming moist.",
    "48": "A drunken man has to be led by a boy, whom he follows stumbling and not knowing whither he goes, for his soul is moist.",
    "49": "It is death to souls to become water, and it is death to water to become earth. Conversely, water comes into existence out of earth, and souls out of water.",
    "50": "Even the sacred barley drink separates when it is not stirred.",
    "51": "It is hard to fight against impulsive desire. Whatever it wants it will buy at the cost of the soul.",
    "52": "It would not be better if things happened to men just as they wish.",
    "53": "It is better to hide our ignorance.",
    "54": "A foolish man is a-flutter at every word. (",
    "55": "Fools, although they hear, are like the deaf. To them the adage applies that \"when present they are absent\".",
    "56": "He said: Bigotry is the sacred disease, and self-conceit tells lies.",
    "57": "Most people do not take heed of the things they find, nor do they grasp them even when they have learned about them, although they think they do.",
    "58": "If all existing things were smoke, it is by smell that we would distinguish them.",
    "59": "In Hades souls perceive by smelling.",
    "60": "Corpses are more fit to be thrown out than dung.",
    "61": "Human nature has no real understanding, only the divine nature has it.",
    "62": "Man is not rational, there is intelligence only in what encompasses him.",
    "63": "What is divine escapes men's notice because of their incredulity.",
    "64": "Although intimately connected with the Logos which orders the whole world, men keep setting themselves against it, and the things which they encounter every day seem quite foreign to them.",
    "65": "As in the nighttime a man kindles for himself (haptetai) a light, so when a living man lies down in death with his vision extinguished, he attaches himself (haptetai) to the state of death; even as one who has been awake lies down with his vision extinguished and attaches himself to the state of Sleep.",
    "66": "Immortals become mortals, mortals become immortals; they live in each other's death and die in each other's life.",
    "67": "There await men after death such things as they neither expect nor have any conception of.",
    "68": "They arise into being-ness and become guardians of the living and the dead.",
    "69": "A man's character is his guardian divinity.",
    "70": "Greater dooms win greater destinies.",
    "71": "The most reliable man understand reliable things and guards them. And Justice will overtake fabricators of lies and false witnesses.",
    "72": "Fire in its progress will catch all things by surprise and judge them.",
    "73": "How can anyone hide from that which never sets?",
    "74": "(When visitors unexpectedly found Heraclitus warming himself by the cooking fire, he said \" Here, too, are gods. \"",
    "75": "They cleanse themselves with others' blood, as if someone were to wash himself by walking in shit were to cleanse himself with shit. It would seem madness to observe such a man who is acting this way. And they pray to images, much as if they were talking to temple edifices, for they do not know what gods and heroes are.",
    "76": "....with night-walkers, magicians, bacchantes, revelers, and participants in the mysteries . What are regarded as mysteries among men are unholy rituals.",
    "77": "Their processions and their phallic hymns would be disgraceful exhibitions were it not that they are done in honor 0f Dionysos. But Dionysos in whose honor they rave and hold revels, is the same as Hades.",
    "78": "The Sibyl with raving mouth utters solemn, unadorned, unlovely words",
    "79": "--",
    "80": "80. Thinking is common to all.",
    "81": "Men should speak with rational mind and thereby hold strongly to that which is shared in common ---- as a city holds on to its law, and even more strongly. For even more strongly all human laws are nourished by the one divine law, which prevails as far as it wishes, suffices for all things, and yet somehow stands above them.",
    "82": "The people should fight for their law as for their city wall.",
    "83": "Law involves obeying the counsel of one.",
    "84": "One man is worth ten thousand if he is first-rate.",
    "85": "The best of men choose one thing in preference to all else, immortal glory in preference to mortal good, whereas the masses simply glut themselves like cattle.",
    "86": "Gods and men honor those slain in battle.",
    "87": "Even a man who is most in 'repute' (reputable?) knows and maintains only what is 'reputed', and holds onto that information. But certainly the justice of Dike will apprehend fabricators and false-witnesses of Lies.",
    "88": "To extinguish hybris is more needed than to extinguish a fire.",
    "89": "It is weariness to keep toiling at the same things so that one becomes ruled by them.",
    "90": "Dogs bark at a person whom they do not know.",
    "91": "What sort of mind or intelligence have they? They believe popular folk-tales and follow the crowd as their teachers, ignoring the adage that the many are bad, the good are few.",
    "92": "Men (he says) are deceived in their knowledge of things that are manifest, even as Homer was who was the wisest of all the Greeks.",
    "93": "Homer deserves to be thrown out of the contests and flogged and Archilochus too.",
    "94": "Hesiod distinguishes good days and evil days, not knowing that every day is like every other.",
    "95": "The Ephesians had better go hang themselves, every man of them, and leave their city to be governed by youngsters, for they have banished Hermadorus, the finest man among them, declaring: \"Let us not have anyone among us who excels the rest. There should be such a one, let him go and live elsewhere.\"",
    "96": "May you have plenty of wealth, you men of Ephesus, in order that you may be punished for your evil ways (",
    "97": "After birth men have the wish to live and to accept their dooms; then they leave behind them children to become dooms in their turn.",
    "98": "Opposition brings concord. Out of discord comes the fairest harmony.",
    "99": "It is by disease that health is pleasant, by evil that good is pleasant, by hunger satiety, by weariness rest.",
    "100": "Men would not have known the name of Justice (dike) if these things had not occurred.",
    "101": "Sea water is at once very pure and very foul: it is drinkable and healthful for fishes, but undrinkable and deadly for men.",
    "102": "Donkeys would prefer hay to gold.",
    "103": "Pigs wash in mud, and domestic fowls in dust or ashes.",
    "104": "The handsomest ape is ugly compared with humankind; the wisest man appears as an ape when compared with a god --- in wisdom, in beauty, and in all other ways.",
    "105": "Man is regarded as childish by a spirit (daemon), just as a boy is by a man.",
    "106": "To God all things are beautiful, good, and right. Men, on the other hand, deem some things right and others wrong.",
    "107": "Doctors cut, burn, and torture the sick, and then demand of them an undeserved fee for such services. They are treating the same things, the (good) cures and diseases.",
    "108": "The way up and the way down are one and the same",
    "109": "In the circumference of the circle the beginning and the end are common.",
    "110": "Into the same rivers we step and do not step. We exist and we do not exist.",
    "111": "For the wool-carder the straight and the winding way are one and the same.",
    "112": "Joints are at once a unitary whole and not a unitary whole. To be in agreement is to differ, the concord-ant is the discord-ant. From many things comes oneness, and out of oneness come the many things.",
    "113": "It is one and the same thing to be living and dead, awake or asleep, young or old. The former aspect in each case becomes the latter, and the latter becomes the former, by sudden unexpected reversal",
    "114": "Hesiod, whom so many accept as their wise teacher, did not even understand the nature of day and night, for they are one.",
    "115": "The name of the bow is life, but its work is death.",
    "116": "The hidden harmony is better than the obvious.",
    "117": "People do not understand how that which is at variance with itself agrees with itself. There is a harmony in the bending back, as in the cases of the bow and the lyre.",
    "118": "Listening not to me but to the Logos, it is wise to acknowledge that all things are one.",
    "119": "Wisdom is one and unique; it is desires and yet does not desire the name of Zeus.",
    "120": "Wisdom is one ---- to know the intelligence which steers all things through all things.",
    "121": "God is day and night, winter and summer, war and peace, satiety But he undergoes transformations, just as (fire) when combined with incenses, is named according to the particular aroma which it gives off.",
    "122": "The sun will not overstep his measures; if he were to do so, the Erinnyes, fiends of Justice, would seek him out for punishment",
    "123": "...the seasons which carry all things along. (100)",
    "124": "Even sleepers are workers and collaborators in what goes on in the universe",
    "125": "Of things which involve sight, hearing and knowledge, these I especially respect."
}
//

// strife : conflict sometimes violent, usually brief or limited in scope. 冲突；纠纷；争吵. 