var abilities =
{
    "Identifying your Abilities": [
        "Adapting:   The ability to adjust, change, alter, modify.",
        "Administrating:  The ability to govern, run, rule.",
        "Analyzing:  The ability to examine, investigate, probe, evaluate.",
        "Building:  The ability to construct, make assemble.",
        "Coaching:  The ability to prepare, instruct, train, equip, develop.",
        "Communicating:  The ability to share, convey, impart.",
        "Competing:  The ability to contend, win, battle.",
        "Computing:  The ability to add, estimate, total, calculate.",
        "Connecting:  The ability to link together, involve, relate.",
        "Consulting:  The ability to advise, discuss, confer.",
        "Cooking:  The ability to prepare, serve, feed, cater.",
        "Coordination:  The ability to organize, match, harmonize.",
        "Counseling:  The ability to guide, advise, support, listen, care for.",
        "Decorating:  The ability to beautify, enhance, adorn.",
        "Designing:  The ability to draw, create, picture, outline.",
        "Developing:  The ability to expand, grow, advance, increase.",
        "Directing:  The ability to aim, oversee, manage, subervise.",
        "Editing:  The ability to correct, amend, alter, improve.",
        "Encouraging:  The ability to cheer, inspire, support.",
        "Engineering:  The ability to construct, design, plan.",
        "Excelling:  The ability to be the best and make my team the best, setting and attaining the highest standard.",
        "Facilitating:  The ability to help, aid, assist, make possible.",
        "Forecasting:  The ability to predict, calculate, see trends, patterns, and themes.",
        "Implementing:  The ability to apply, execute, make happen.",
        "Improving: The ability to better, enhance, further, enrich.",
        "Influencing:  The ability to affect, sway, shape, change.",
        "Landscaping:  The ability to garden, plant, improve.",
        "Leading:  The ability to pave the way, direct, excel, win.",
        "Learning:  The ability to study, gather, understand, improve, expand self.",
        "Managing:  The ability to run, handle, oversee.",
        "Mentoring:  The ability to advise, guide, teach.",
        "Motivating:  The ability to provoke, induce, prompt.",
        "Negotiating:  The ability to discuss, consult, settle.",
        "Operating:  The ability to run mechanical or technical things.",
        "Organizing:  The ability to simplify, arrange, fix classify, coordinate.",
        "Performing:  The ability to sing, speak, dance, play an instrument, act out.",
        "Persevering:  The ability to see things to completion, persisting at something until it is finished.",
        "Pioneering:  The ability to bring about something new, groundbreaking, original.",
        "Planning:  The ability to arrange, map out, prepare.",
        "Promoting:  The ability to sell, sponsor, endorse, showcase.",
        "Recruiting:  The ability to draft, enlist hire, engage.",
        "Repairing:  The ability to fix, mend, restore, heal.",
        "Researching:  The ability to seek, gather, examine, study.",
        "Resourcing:  The ability to furnish, provide, deliver.",
        "Serving:  The ability to help, assist, fulfill.",
        "Shopping:  The ability to collect, or obtain things, getting the highest quality for the best price",
        "Strategizing:  The ability to think ahead, calculate, scheme.",
        "Teaching:  The ability to interpret, decode, explain, speak.",
        "Traveling:  The ability to journey, visit, explore.",
        "Visualizing: The ability to picture, imagine, envision, dream, conceptualize.",
        "Welcoming:  The ability to entertain, greet, embrace, make comfortable.",
        "Writing:  The ability to compose, create, record."
    ]
}