var evangelism_assessment_questionaire = [
"In conversations, I like to approach topics directly, without much small talk or beating around the bush.",
"I have a hard time getting out of bookstores or libraries without getting a bunch of books that will help me better understand issues being debated in society.",
"I often tell stories about my personal experiences in order to illustrate a point I am trying to make.",
"I am a \"people person\" who places a high value on friendship.",
"I enjoy including or adding new people to activities I am involved in.",
"I see needs in people\'s lives that others often overlook.",
"I do not shy away from putting a person on the spot when it seems necessary.",
"I tend to be analytical.",
"I often identify with others by using phrases like \"I used to think that too\" or \"I once felt the way you do.\"",
"Other people have commented about my ability for developing new friendships.",
"To be honest, even if I knew the answers, I am more comfortable having someone \"better qualified\" explain Christianity to my friends.",
"I find fulfillment in helping others often in behind-the-scenes ways.",
"I do not have a problem confronting my friends with the truth even if it risks hurting the relationship.",
"In conversations, I naturally focus on the questions that are holding up a person\'s spiritual progress.",
"When I tell people of how I came to Christ, I have found that they have been interested in hearing it.",
"I would rather delve into personal life issues than abstract theological ideas.",
"If I knew of a high quality outreach event that my friends would enjoy, I would make a big effort to bring them.",
"I prefer to show love through my actions more than my words.",
"I believe that real love often means telling someone the truth, even when it hurts.",
"I enjoy discussions and debates on difficult questions.",
"I intentionally share my mistakes with others when it will help them relate to the solutions I have found.",
"I prefer getting involved in discussions concerning a person\'s life before dealing with the details of their beliefs.",
"I tend to watch for spiritually strategic events to bring people to (such as Christian concerts, outreach events, seeker services).",
"When people are spiritually closed, I have found that my quiet demonstrations of Christian love sometimes make them more receptive.",
"A motto that would fit me is: \"Make a difference or a mess, but do something.\"",
"I often get frustrated with people when they use weak arguments or poor logic.",
"People seem interested in hearing stories about things that have happened in my life.",
"I enjoy long talks with friends.",
"I am always looking for a match between the needs and interests of my friends and the various events, books, etc., that they would enjoy or benefit from.",
"I feel more comfortable physically assisting a person in the name of Christ than getting involved in religious discussions.",
"I sometimes get in trouble for lacking gentleness and sensitivity in the way I interact with others.",
"I like to get at the underlying reasons for opinions that people hold.",
"I am still amazed at how God brought me to faith in Him and I am motivated to tell people about it.",
"People generally consider me to be an interactive, sensitive, and caring kind of person.",
"A highlight of my week would be to take a guest with me to an appropriate church event.",
"I tend to be more practical and action-oriented than philosophical and idea-oriented."
]